version: 1.0.{build}
image: Ubuntu
install:
  - npm install
build_script:
  - npm run build
on_success:
  - git config --global credential.helper store
  - echo https://$GITHUB_TOKEN:@github.com > /home/appveyor/.git-credentials
  - npm run deploy